steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/ub-2023-hack/kaizntree-backend-image', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/ub-2023-hack/kaizntree-backend-image']
images:
- gcr.io/ub-2023-hack/kaizntree-backend-image